---
name: User Story
about: Use this template when creating a new user story
title: "UserStory: {{Enter User Story Name}}"
---

As a ___, I want to ____ so that

**Acceptance Criteria**
- [ ] Criteria 1

**Sub Tasks**
- [ ] Task 1
- [ ] Task 2

**Additional Comments**
