name: ci
on:
  push:
  pull_request:
jobs:
  fmt_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && yarn --frozen-lockfile && yarn format
  lint_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && yarn --frozen-lockfile && yarn lint
