name: ci
on:
  push:
  pull_request:
jobs:
  fmt_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && yarn --frozen-lockfile && yarn format
  lint_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && yarn --frozen-lockfile && yarn lint
  test_server:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      MONGO_URI: ${{secrets.MONGO_URI}}
      NODE_ENV: ${{secrets.NODE_ENV}}
    steps:
      - uses: actions/checkout@v2
      - name: Start MongoDB Container
        run: docker-compose up --build -d
      - name: Install dependencies and run tests
        run: cd backend && yarn --frozen-lockfile && yarn test
      - name: Cleanup
        run: docker-compose down

